apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: app-of-apps
spec:
  project: default
  source:
    path: argo-cd-app-of-apps/apps
    repoURL: 'https://github.com/senolerd/TWN-online-boutique-gitops.git'
    targetRevision: HEAD
  destination:
    name: in-cluster 
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
