apiVersion: apps/v1
kind: Deployment
metadata:
  name: "paymentservice-deployment"
  labels:
    app: "paymentservice"
spec:
  replicas: {{ .Values.paymentservice.replica }}
  selector:
    matchLabels:
      app: "paymentservice"
  template:
    metadata:
      labels:
        app: "paymentservice"
    spec:
      containers:
      - name: "paymentservice"
        image: "{{ .Values.paymentservice.imguri }}"
        ports:
        - containerPort: {{ .Values.paymentservice.port }}
        env:
        - name: PORT
          value: "{{ .Values.paymentservice.port }}"
        - name: AD_SERVICE_ADDR
          value: "{{ .Values.adservice.name }}:{{ .Values.adservice.port }}"
        - name: CART_SERVICE_ADDR
          value: "{{ .Values.cartservice.name }}:{{ .Values.cartservice.port }}"
        - name: CHECKOUT_SERVICE_ADDR
          value: "{{ .Values.checkoutservice.name }}:{{ .Values.checkoutservice.port }}"
        - name: CURRENCY_SERVICE_ADDR
          value: "{{ .Values.currencyservice.name }}:{{ .Values.currencyservice.port }}"
        - name: EMAIL_SERVICE_ADDR
          value: "{{ .Values.emailservice.name }}:{{ .Values.emailservice.port }}"
        - name: FRONTEND_SERVICE_ADDR
          value: "{{ .Values.frontend.name }}:{{ .Values.frontend.port }}"
        - name: PAYMENT_SERVICE_ADDR
          value: "{{ .Values.paymentservice.name }}:{{ .Values.paymentservice.port }}"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "{{ .Values.productcatalogservice.name }}:{{ .Values.productcatalogservice.port }}" 
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "{{ .Values.recommendationservice.name }}:{{ .Values.recommendationservice.port }}" 
        - name: SHIPPING_SERVICE_ADDR
          value: "{{ .Values.shippingservice.name }}:{{ .Values.shippingservice.port }}" 
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        - name: ENABLE_SHOPPING_ASSISTANT
          value: "false"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
        - name: GCP_PROJECT
          value: "hello"
        - name: GOOGLE_CLOUD_PROJECT
          value: "world"
---
apiVersion: v1
kind: Service
metadata:
  name: "paymentservice"
spec:
  selector:
    app: "paymentservice"
  ports:
  - protocol: TCP
    port: {{ .Values.paymentservice.port }}
    targetPort: {{ .Values.paymentservice.port }}
