"apiVersion": "gateway.k8s.aws/v1beta1"
"kind": "TargetGroupConfiguration"
"metadata":
  "name": "frontend-tg"
"spec":
  "defaultConfiguration":
    "healthCheckConfig":
      "healthCheckPath": "/_healthz"
    "targetType": "ip"
  "targetReference":
    "name": "frontend"
