apiVersion: argoproj.io/vialpha1
kind: Application 
metadata:
  name: app-of-apps
spec:
  destination:
    name: in-cluster 
    namespace: argocd
  source:
    path: apps
    repoURL: 'https://github.com/senolerd/TWN-online-boutique-gitops/tree/main/argo-cd-app-of-apps'
    targetRevision: HEAD
  project: default
    # syncPolicy:
    #   automated:
    #     prune: true 
    #     selfHeal: true