apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: app-of-apps
spec:
  destination:
    name: in-cluster 
    namespace: argocd
  source:
    path: argo-cd-app-of-apps/apps
    repoURL: 'https://github.com/senolerd/TWN-online-boutique-gitops.git'
    targetRevision: HEAD
  project: default
    # syncPolicy:
    #   automated:
    #     prune: true 
    #     selfHeal: true