"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "finalizers":
  - "resources-finalizer.argocd.argoproj.io"
  "name": "platform-tf"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "gateway-system"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "path": "argocd/platform"
    "repoURL": "https://github.com/senolerd/TWN-online-boutique-gitops.git"
    "targetRevision": "HEAD"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
    "retry":
      "backoff":
        "duration": "10s"
        "factor": 2
        "maxDuration": "2m"
      "limit": 5
    "syncOptions":
    - "CreateNamespace=true"
